### Good request
POST http://localhost:8000/vm/start

{
    "cpu_count": 4,
    "mem_size_gb": 32,
    "image": "debian:bookworm"
}

### Stop (change ID)
POST http://localhost:8000/vm/d498c9e0921c43d48d45247ecce8557e/stop

### CPU count too high
POST http://localhost:8000/vm/start

{
    "cpu_count": 400,
    "mem_size_gb": 32,
    "image": "debian:bookworm"
}